/**
 * Created by jhoran on 8/9/2019.
 */

public with sharing class trac_OrderRefundCreditConstants {

    public static final String STATUS_REQUIRES_APPROVAL = 'Requires Approval';
    public static final String STATUS_APPROVED = 'Approved';
    public static final String STATUS_DECLINED = 'Declined';
    public static final String STATUS_CLOSED = 'Closed';
    public static final String STATUS_DRAFT = 'Draft';
    public static final String STATUS_CANCELLED = 'Cancelled';
    public static final String STATUS_NEW = 'New';

}