/**
 *  @description Constants for Contact object
 *  @author      Jeremy Horan, Traction on Demand.
 *  @date        9/11/2019
 */
public with sharing class trac_ContactConstants {
    public static final String ORIGIN_SALESFORCE = 'Salesforce';
    public static final String ORIGIN_UCID = 'UCID';
    public static final String ORIGIN_OMS = 'OMS';

    public static final String CHANNEL_PHONE = 'Phone';

    public static final String BUSINESS_UNIT_BAY = 'Hudson\'s Bay';
    public static final String BUSINESS_UNIT_MHF = 'MHF';
}