{
    "_v": "19.1",
    "_type": "customer",
    "_resource_state": "d21d717f04d08dd612e84969933e710a1e5a260b8649e3af9d465604e5df703d",
    "auth_type": "registered",
    "creation_date": "2020-01-17T14:30:20.136Z",
    "customer_id": "abRxEDBVONuKdnVGfTqfWebPHE",
    "customer_no": "00001501",
    "email": "jsmith1@test.com",
    "enabled": true,
    "last_modified": "2020-01-17T14:30:20.141Z",
    "last_name": "Smith",
    "login": "jsmith1"
}